name: Create pre-release version

on:
  push:
    branches: [ Stage2 ]

jobs:
  pre_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install
    
    - name: Populate auth file
      shell: bash
      run: 'echo ${{secrets.AUTH_URL}} > ./AUTH_URL.txt'
    
    - name: Authenticate Dev Hub
      run: 'sfdx force:auth:sfdxurl:store -f ./AUTH_URL.txt -a devhub -d'

    - name: Create new version
      run: |
        sfdx force:package:version:create -x -p "TestPackage" -w 60 --codecoverage
        temp_id=$(grep -o "04t[[:alnum:]]\{15\}" sfdx-project.json | tail -n1)
        echo "version_id=${temp_id}" >> $GITHUB_ENV
    
    - name: Check code coverage
      run: |
        test $(sfdx force:package:version:report -p "$version_id" --json | jq .result.HasPassedCodeCoverageCheck) = 'true'
    
    - name: Install new version in Dev Hub
      run: |
        sfdx force:package:install -p "$version_id" -u devhub --wait 10 --publishwait 10
    
    - name: Store new version id
      run: |
        git config user.name "ecommercebot"
        git config user.email "<>"
        git add sfdx-project.json
        git commit -m "Updating new pre-release version"
        git push